### ISSUE TITLE
http-server

### ISSUE THREAD

**Issue by fede220** [up209d/ResourcesSaverExt#10]
Hi sorry i'm not expert, downloaded this page http://www.coolmath-games.com/sites/cmatgame/files/public_games/22869/ with resources by XHR request but how to execute http-server? Possible add "file:///" in whitelist domains of core.js work offline? Thank you very much.

**Comment by up209d** [comment]
`Core.js` is the file in the game package not in my extension, you can make any basic & simple http-server such as node http-server, apache, nginx ... I am sorry but it s 2018, making a http-serve to run application is very common and mandatory. You can search how to make http-server on Youtube and there will be a thousand of video tutorial showing up for you.
