### ISSUE TITLE
Problem with dynamic web page

### ISSUE THREAD

**Issue by fede220** [up209d/ResourcesSaverExt#11]
Hi i'm download this web page https://kiwiirc.com/client but i display blank page in browser with errors. It's possible download this dynamic web page at current state and view correctly in browser? Thank you very much.

**Comment by fede220** [comment]
I'm load the web page from the link and I disable the internet connection, the web page continues to work after loading at current state.

**Comment by up209d** [comment]
@fede220 It is all good if you don't mind to look into fundamental of the web industry, try to get yourself some decent tutorials. I think you are lacking few concept ideas behind web development.
