### ISSUE TITLE
Problems with Vivaldi

### ISSUE THREAD

**Issue by anpsoft** [up209d/ResourcesSaverExt#13]
Hi!

Vivaldy is full compatible chromium browser for any extantions what i use
but this not work :(

when i press Save All resources. nothing happend

ps: i test it in Chrome, all work fine, but i not use Chrome 

Thanks

**Comment by up209d** [comment]
Hi anpsoft, it is probably because Vivaldi creator did cut-off some core API from Chromium. The extension mainly rely on the Devtool API provided by Chrome Core, so it can get the Sources information. I am sorry that might be beyond of my ability to make Vivaldi work.
