### ISSUE TITLE
Network Failed Issue when Downloading

### ISSUE THREAD

**Issue by jinuem** [up209d/ResourcesSaverExt#14]
It fetches the files and It starts the download but download fails.
May i know whats the issue here?
![screenshot 2018-10-03 15 10 39](https://user-images.githubusercontent.com/3512723/46402895-a2424b00-c71e-11e8-8483-a7908471d87e.png)

**Comment by up209d** [comment]
@jinuem Oops, It would be a file size limit for data URI downloading, I shall fix it now. Let you check soon!

**Comment by up209d** [comment]
@jinuem Does it happen with some specific websites or you have problem with all the websites. Please see this support topic from Google, it might come from the browser. 

`https://support.google.com/chrome/answer/2898334?hl=en`

> "Network failed"
> If you see "NETWORK_FAILED" when you try to install something from the Chrome Web Store, unwanted software could be blocking the installation.
> 
> To fix the error:
> 
> First, remove the unwanted software. Then, try to install the app, extension, or theme again. 
> If you still can't install the app, extension, or theme, reinstall Chrome.

**Comment by rntchi** [comment]
Same thing here. Disabled everything, on every site and every flavor of chrome, this happens. The only case where it does not happen is when I load the extension unpacked on Chrome Dev.

**Comment by up209d** [comment]
@jinuem @rntchi Please, check out the new unpacked version to see whether the problem is fixed?
