### ISSUE TITLE
Network error when downloading pack with files

### ISSUE THREAD

**Issue by rntchi** [up209d/ResourcesSaverExt#16]
Tried this even on a fresh Chrome installation, whenever I try to download the packed files I get a network error, the download address being a blob contained within the extension URL. Not sure if the problem is on my browser or not. It used to not happen a few weeks ago!

**Comment by rntchi** [comment]
The problem did not occur when I loaded the unpacked extension on Chrome Dev.

**Comment by up209d** [comment]
@rntchi The ext on Chrome Webstore and the unpacked one on Github is exactly identical. Could be some internal policy changes for Chrome official extensions that limit the download size of `Blob`. Is your downloading zip file big?

**Comment by vuolter** [comment]
> 
> 
> The problem did not occur when I loaded the unpacked extension on Chrome Dev.

Just tried, but doesn't works for me neither that way 😢

**Comment by up209d** [comment]
@vuolter Hi mate, not sure whether it works but could you try the new unpacked version that I have pushed?

**Comment by vuolter** [comment]
I just tested the latest unpacked version and fails too, but not too bad because revision https://github.com/up209d/ResourcesSaverExt/tree/b7078b6d274c766cc95beac40c1ee2c7f174ab6a is working fine both in unpack mode and overwriting files directly in chrome. 😄

**Comment by up209d** [comment]
@vuolter Arghhh, my bad, just pushed the latest one and surely it will work. Thank you for your testing mate.

**Comment by vuolter** [comment]
@up209d Definitely working fine for me. Thanks man. ❤️

**Comment by rntchi** [comment]
Absolutely working, bonus points for you as now the extension allows us to select where to save the file pack. Thanks!
