### ISSUE TITLE
Default Zip to URL

### ISSUE THREAD

**Issue by jaegertros** [up209d/ResourcesSaverExt#18]
Would it be possible for me to make a modification so the downloaded zip file defaults to the cleaned up version of the URL (/(\\|\/|:|\*|\?|"|<|>|\|)/g,"_") it is being downloaded from? I tried
`filename:` 'All Resources/all.zip'`
to
`filename: finalURI.zip`
but that didn't work. I'm not exactly shocked because I have no idea what I'm doing, but hey, I tried before annoying you :)

Thanks for a great extension!

**Comment by up209d** [comment]
@jaegertros Hey bro, I am not sure what would you want to achieve? Could you clarify it with more details, maybe I can help :D

**Comment by jaegertros** [comment]
@up209d appreciate the quick response! I am using your extension to help with my thesis research so I can grab articles and related stuff from pages, so super helpful (more so than just saving the article or whatever itself). The filenames default to "all.zip" in the "All Resources" folder of downloads. I was hoping to have it default to always naming the zip file after the URL where it was gotten from. I didn't know how Windows would handle it if the extension tried to use invalid filepath characters, and I was trying to show an attempt at cleaning that up. But honestly, it doesn't make a difference to me if the characters are just removed or replaced by anything else. It would just save me a lot of time trying to manually clean up the url name and then renaming the zip files or also save me from this "all (68).zip" mess that I am making for myself.

For example, if I saved this page:

currently - all.zip

hopeful for - anything alone these lines 
httpsgithub.comup209dResourcesSaverExtissues18.zip
https  github com up209d ResourcesSaverExt issues 18.zip
github.com_up209d_ResourcesSaverExt_issues_18.zip

**Comment by up209d** [comment]
@jaegertros hey bro, you might need to take the tab url first like this
```
function downloadCompleteZip(blobWriter, callback) {
	blobWriter.close(function (blob) {
            chrome.tabs.get(chrome.devtools.inspectedWindow.tabId, function (tab) {
		var domain = tab.url.replace(/(\|/|:|*|?|"|<|>||)/g,"_"); 
               chrome.downloads.download({
			url: URL.createObjectURL(blob),
			filename: 'All Resources/'+domain+'.zip',
			saveAs: false
		}, function () {
			if (chrome.runtime.lastError) {
				callback(false);
			} else {
				callback(true);
			}
		});
            });	
	});
}

```
