### ISSUE TITLE
paths in downloaded html file are to remote locations, not the local downloaded assets

### ISSUE THREAD

**Issue by happysailingdude** [up209d/ResourcesSaverExt#19]
Please see this example:

1. Browse here in Chrome https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/

2. Open developer tools, click on ResourceSaver tab and click on "Save all resources"

3. get this locally (which looks very promising)

![image](https://user-images.githubusercontent.com/5772853/49605712-2b793680-f989-11e8-949a-f1d11819d379.png)

4. Open getbootstrap.com/getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/index.html 

I was expecting to see paths pointing to the local copies of assets, but instead the paths are to the remote assets.

I now have a local copy of jquery-3.2.1.slim.min.js because ResourcesSaverExt has helpfully downloaded it BUT the index.html file that references it is still pointing to the remote version of https://code.jquery.com/jquery-3.2.1.slim.min.js 

is there a way to make the page we download be modified so that it points to the downloaded copies of all assets? (or am i missing something)?

Thanks in advance :)

**Comment by up209d** [comment]
Hi @happysailingdude, the tool is targeted to get all the assets `untouchedly`. It is just a greedy and naive downloading tool to fetch all possible files from the server and keep the same structure as the server. Modifying content inside assets is currently out of scope. I am afraid that you might need another extension to fulfil your specific requirement.

**Comment by happysailingdude** [comment]
@up209d Thank you very much for your reply and for explaining; all understood.. thank you very much. You're tool is still very helpful in it's current form so thank you (although I do think a tick box to "update paths to localised versions of all assets" would be a killer feature if ever you got around to it :) thanks again. Best, Nick
