### ISSUE TITLE
Error when download file with invalid filename 

### ISSUE THREAD

**Issue by xiaopan321** [up209d/ResourcesSaverExt#2]
Hi. I noticed that you informed users with error message when meet Chrome.runtime.error.

But I have problem with that because the filename of the download file is invalid.For example:
`All Resources/test /.toDownload`
Both the empty space after `test` and `.` at the first of the filename are invalid on the Mac.

Then the downloading process stopped which is what I won't expect to happen.
So would you like to add the feature to turn the invalid filename valid. I think it's easy to delete the invalid empty space character and the `.` character. And maybe some better method...

**Comment by up209d** [comment]
Great spot! I still missed some violating file path. I've just updated the fix covering your case. Hope that will work well. Thank you very much.
