### ISSUE TITLE
Hangs if compress option is unchecked on WIndows

### ISSUE THREAD

**Issue by oscarryz** [up209d/ResourcesSaverExt#22]
Works fine on mac, but in Windows when the "compress" option is not checked the download hangs.

Great extension btw.

**Comment by up209d** [comment]
@oscarryz Hey mate, thanks for reporting the bug, I'll have a look, btw I am planning to remove that option so compressing & download will be the only choice in the future.

**Comment by oscarryz** [comment]
Wouldn't that add an extra step for the user (uncompress the zip file?) 

My use case is the next:
- Go to my website, click on page 1 -> download
- click on page 2 -> download

I have now two zip files
mysite.com.zip
mysite.com(1).zip

I have to uncompress them and then merge them together  (currentlyl I just have to merge them) 

Oh which btw, would there be a way to override files? For instance if page 1 and page 2 share the same CSS I have now mycss.css and mycss(1).css, I know this is something the OS does for you, just wondering how difficult that is. 

Again, thanks for the awesome extension.

**Comment by up209d** [comment]
Yes mate, that is done by Chrome natively, we don't have the option to tell Chrome to override the zip file. Thank you for using the extension.
