### ISSUE TITLE
Not all resources are downloaded from the current tab. 

### ISSUE THREAD

**Issue by MaheshBaisani** [up209d/ResourcesSaverExt#25]
HI,

First of all thank you for providing a great tool..
When click on Save all resources button it downloads all the resources files of all domain from the current tab except few domains like ng://, webpack:// which are will available some times for angular/reactJS app.
[
![resourcewebpackerror](https://user-images.githubusercontent.com/47409639/58754605-b9c21580-84f1-11e9-8085-1a91b379792c.JPG)
[](url)](url
![downloadwebpack](https://user-images.githubusercontent.com/47409639/58754651-bda26780-84f2-11e9-8489-d030565db0ce.JPG)
)
Please find the above screenshot for your reference where all tick marked resources are downloaded and "X" marked contents are not able to downloaded.

Please kindly check and do needful.

**Comment by up209d** [comment]
@MaheshBaisani I believe it won't skip `webpack` and `ng` protocol, I did test it before, are you using the 0.1.6 version atm?
<img width="1154" alt="Screen Shot 2019-06-02 at 3 10 26 pm" src="https://user-images.githubusercontent.com/3246881/58757083-9bd3cf80-8548-11e9-9ec1-71103c67d858.png">

**Comment by MaheshBaisani** [comment]
@up209d , Thank you for your quick reply. Yes i am using latest version 0.1.6 only. 
![Capture](https://user-images.githubusercontent.com/47409639/58758310-5064f580-8537-11e9-8e75-1c39f765e046.JPG)
, Now also i tried with some online example from below link (I run the index.html file and it contains the webpack files.) but still no luck. I am not able to get the webpack content.
https://github.com/Booyanach/here-map/tree/master/docs

**Comment by up209d** [comment]
@MaheshBaisani I found the problem, just fixed and pushed, can you use the unpacked version in this repo to test, instead of the official one on Chrome Webstore?

**Comment by MaheshBaisani** [comment]
Sure @up209d , I will check and let you know the status.

**Comment by up209d** [comment]
@MaheshBaisani Cheers mate, thank you for pointing out the issue. I gonna update to Webstore tomorrow.
