### ISSUE TITLE
Download file warning

### ISSUE THREAD

**Issue by shanligang** [up209d/ResourcesSaverExt#3]
When I download resources, the page js file will always be warned, how to solve? My Google Chrome version is 63.0.3239.84

**Comment by up209d** [comment]
Might be a special case, could you give me more visual about the warning, since it is running well with the latest version of Chrome afa i am using now.

**Comment by shanligang** [comment]
![image](https://user-images.githubusercontent.com/8465913/34194719-0f2fcc72-e595-11e7-9af2-88306e7b58b3.png)

**Comment by shanligang** [comment]
just like this

**Comment by shanligang** [comment]
![image](https://user-images.githubusercontent.com/8465913/34194855-c082c4de-e595-11e7-97f2-a7d8d261ca2a.png)

**Comment by up209d** [comment]
Oh, this is the issue come from the security feature of Chrome itself, there is nothing that the extension can do. You can try to disable that feature by:

Settings > Privacy and security > Turn off the option 'Protect you and your device from dangerous sites'

**Comment by shanligang** [comment]
I am sorry, It still doesn't work.

**Comment by shanligang** [comment]
Is there any other way?

**Comment by up209d** [comment]
I am not 100% sure that saving files as .js extension will have to be passed Chrome security warning. Saving those file as other extension such as .jsx might come through straightly. I can quickly make an option for that, but it means after downloading, you might need to change extension of all .jsx files back to .js files manually by yourself.

**Comment by shanligang** [comment]
I solved this problem by using compressed files. I was referring to this project [.](https://github.com/gildas-lormeau/zip.js) If you want my code, you can tell me your email address. thank you very much for your help!

**Comment by shanligang** [comment]
https://github.com/gildas-lormeau/zip.js

**Comment by up209d** [comment]
Great mate, to hear you solved the issue! So, we zip the js files before downloading, and unzip it after downloading?

**Comment by shanligang** [comment]
My code is written a bit poor, so I do not want to use github to upload code, I hope to send you by mail.

**Comment by up209d** [comment]
Okay mate, you can send me via up209d@gmail.com. I think it is a brilliant idea to compress assets even not js files, pack everything up to one compressed blob file and download everything at once. Thank you for your contribution, i am really appreciated.

**Comment by shanligang** [comment]
Ohh. When I send mail to remind me that the file has security issues, so I submitted it with github. You can modify the code I, in some cases I did not consider, you need to improve. Haha

**Comment by up209d** [comment]
Alright no problem mate, anyway, sending js files via Gmail is prohibited even with a compressed file, but you still can do the sharing by uploading the file to Google Drive and share that file to my email. Cheers!

**Comment by shanligang** [comment]
:ok_hand:

**Comment by up209d** [comment]
I have done the update with new compressing option. Could you try it and let me know if there is any issue? Cheers mate!

**Comment by shanligang** [comment]
I read your updated code and now it works fine. I need to learn from you. 😄

**Comment by up209d** [comment]
Yay! We re both learning from each other. 👍
