### ISSUE TITLE
Downloading appends .txt not .zip to the file

### ISSUE THREAD

**Issue by sticker592** [up209d/ResourcesSaverExt#31]
I had to manually change the extension.

**Comment by duc-duong-energetiq** [comment]
> I had to manually change the extension.

Ah, it wasn't prepared for zip file type, I gonna fix this soon 👍

**Comment by Gregory-Ledray** [comment]
Sometimes Chrome changes the extensions of some files when you're downloading them from an extension. For instance, you're not allowed to download a file with the extension, ".mhtml" even though it's a valid format. When you try to download such a file the extension is replaced with ".txt". I think this is what is happening to you.

That being said I haven't had this problem. Do you have steps to reproduce it?
