### ISSUE TITLE
Download resources across multiple pages

### ISSUE THREAD

**Issue by roflware** [up209d/ResourcesSaverExt#35]
Apologies as this probably is more or a feature request, but would find this to be loads useful on client side JS navigable pages where crawling doesn't seem to do the trick. 

Is there a way to seamlessly aggregate all resources on a page and continue acquiring resources for each subsequent page where the user navigates? Such as, a start and then an end function, where then everything is zipped up into a single archive for full offline viewing. 

Assuming that this doesn't exist and would be possible, could this feature be added in if it wouldn't be too much trouble for you?

Thanks in advance!

**Comment by up209d** [comment]
sorry mate, i think it is not possible.

**Comment by roflware** [comment]
No worries, appreciate the reply.
