### ISSUE TITLE
need to download the images

### ISSUE THREAD

**Issue by hsl1** [up209d/ResourcesSaverExt#37]
from this site http://preview.themeforest.net/item/adventure-tours-wordpress-tourtravel-theme/full_screen_preview/12781942?_ga=2.259441864.352627645.1599299052-828512567.1599211047&_gac=1.217367074.1599299052.EAIaIQobChMIhfCzsJXP6wIVU_hRCh1wAQV6EAAYASAAEgIII_D_BwE
i cant download the images from there, all ignored

![image](https://user-images.githubusercontent.com/11902467/92302718-31d58180-ef66-11ea-9be6-72a2ba50ec9c.png)

it would be great if you add that option from  http://preview.themeforest.net + theme and not this link exactly

i can find the images on the network tab

**Comment by up209d** [comment]
![Screen Shot 2020-09-07 at 12 12 18 am](https://user-images.githubusercontent.com/3246881/92327715-00140600-f09f-11ea-9337-7a180176ef98.png)

not sure why you got download issues, i don't have that problem. Try to click on `remove frame` to get to the real page. But again, this extension is for general purpose, it is not targeting on any specific website or service.
