### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by Gregory-Ledray** [up209d/ResourcesSaverExt#39]
I'd like to modify this extension to help me clone entire websites and republish it under a different name since the use-case of such a cloning will be different. Unfortunately I don't see a license so I'm not legally allowed to do that. Could you add a permissive software license like MIT to this repository please?

**Comment by duc-duong-energetiq** [comment]
Sorry that I published the code so people can folk and modify as their desire, but I don't have the intention to let it republished as the other one.
