### ISSUE TITLE
Audio and video files saved using ResourcesSaver are imcomplete

### ISSUE THREAD

**Issue by Anonymity** [up209d/ResourcesSaverExt#48]
Version: 0.1.8

### Example pages:
https://interactive-examples.mdn.mozilla.net/pages/tabbed/audio.html
https://interactive-examples.mdn.mozilla.net/pages/tabbed/video.html

### Steps to reproduce:
Open the links above.
Open Devtools and switch to ResourcesSaver tab.
Check "Include all assets by XHR requests (require page reload)."
Play the audio/video.
Switch back to ResourcesSaver and click save all resources.
Find and extract t-rex-roar.mp3 and flower.webm respectively in the zip file.
Download these files using browser's builtin download function.
Compare the files.

### Expected behavior:
Files saved using ResourcesSaver are identical to files downloaded using browser's builtin download function.

### Actual behavior:
For t-rex-roar.mp3, only a small part is saved. For flower.webm, file cannot be played.

**Comment by up209d** [comment]
I have expected behavior with `2.0.2` atm
