### ISSUE TITLE
Option include all assets by XHR requests is missing in v2

### ISSUE THREAD

**Issue by FaxMan2** [up209d/ResourcesSaverExt#59]
Hello I love this extension and I use it almost on a daily basis, I like using the include all assets by XHR requests option since it gets audio and images, but the problem is that the option not there anymore in v2. The only options are Ignore "no content files", and beautify files.

**Comment by up209d** [comment]
> Hello I love this extension and I use it almost on a daily basis, I like using the include all assets by XHR requests option since it gets audio and images, but the problem is that the option not there anymore in v2. The only options are Ignore "no content files", and beautify files.

Hey mate, it doesn't have that option anymore because it now defaults to having that tick always on. It could be a bug somewhere that left you unexpected results. Let me check.

**Comment by up209d** [comment]
> Hello I love this extension and I use it almost on a daily basis, I like using the include all assets by XHR requests option since it gets audio and images, but the problem is that the option not there anymore in v2. The only options are Ignore "no content files", and beautify files.

in the meantime, could you check the `2.0.2` unpacked version in this repo, I believe it would solve your problem, I m also publishing the version to Chrome ext store atm.
