### ISSUE TITLE
Panel not appearing in any version number

### ISSUE THREAD

**Issue by KrautGTI** [up209d/ResourcesSaverExt#60]
Howdy! The Resource Saver Panel does not appear in any version number. I deleted and redownloaded it; that did not fix it. I am running the latest version of chrome on macOS, and I am not running the extension on (https://chrome.google.com/***). I have used this extension for over a year and love it! After the last update, it disappeared.

**Comment by up209d** [comment]
> Howdy! The Resource Saver Panel does not appear in any version number. I deleted and redownloaded it; that did not fix it. I am running the latest version of chrome on macOS, and I am not running the extension on (https://chrome.google.com/***). I have used this extension for over a year and love it! After the last update, it disappeared.

Are you running in incognito mode?

**Comment by KrautGTI** [comment]
> > Howdy! The Resource Saver Panel does not appear in any version number. I deleted and redownloaded it; that did not fix it. I am running the latest version of chrome on macOS, and I am not running the extension on (https://chrome.google.com/***). I have used this extension for over a year and love it! After the last update, it disappeared.
> 
> Are you running in incognito mode?

No, Regular Chrome Browser Signed in.

**Comment by KrautGTI** [comment]
I have also tried disabling / enable, remove extension and re download, and disabled all other extensions, and still nothing

**Comment by up209d** [comment]
> I have also tried disabling / enable, remove extension and re download, and disabled all other extensions, and still nothing
> 
> 

Does it happen also when loading local extension from this repo (2.0.4). The one on store is 2.0.3 and it has handled error bug.

**Comment by KrautGTI** [comment]
I have not done a local extension unpack before, which file in this repo do I upload to chrome://extensions/ ?

**Comment by KrautGTI** [comment]
Figured it out, on reload it appeared! Thanks! 
<img width="945" alt="Screen Shot 2022-09-30 at 9 54 05 PM" src="https://user-images.githubusercontent.com/94489438/193386546-da3918b2-7e0b-456a-bfee-a05468283cc4.png">

<img width="423" alt="Screen Shot 2022-09-30 at 9 52 23 PM" src="https://user-images.githubusercontent.com/94489438/193386536-d92f07b0-1d7b-4a78-9d80-a20af28b1260.png">

**Comment by KrautGTI** [comment]
To confirm, v2.0.4 works, and the change version within 2.0.4 also works. 2.0.3 does nothing at all. Cheers!
