### ISSUE TITLE
Retrieve or generate package.json

### ISSUE THREAD

**Issue by CaledoniaProject** [up209d/ResourcesSaverExt#63]
Nice extension, it works for webpack based projects. But do you have any ideas on how to generate packages.json from existing node_modules?

I'm also not sure whether webpack would include package.json in the artifacts.

**Comment by up209d** [comment]
> Nice extension, it works for webpack based projects. But do you have any ideas on how to generate packages.json from existing node_modules?
> 
> I'm also not sure whether webpack would include package.json in the artifacts.

That would be not possible since the `package.json` file is not included in the source map

**Comment by CaledoniaProject** [comment]
OK, Understood.
