### ISSUE TITLE
Problems with encode

### ISSUE THREAD

**Issue by JulianoDotto** [up209d/ResourcesSaverExt#7]
The extension worked very well, but when there is a file with a special character like "ç" it seems to break.

The site has a file whose name is: "53_Jean_Goçalves".
And when I use the extension it saves it with the following name: "53_Jean_Go% C3% A7alves".

Maybe there's a way to use Unicode to save file's name.

**Comment by up209d** [comment]
Thanks for the spot mate, I will update it soon.
